### ISSUE TITLE
I having problem with progressbar

### ISSUE THREAD

**Issue by Gabit07** [TessFerrandez/research-papers#2]
ImportError                               Traceback (most recent call last)
<ipython-input-19-c196dbddd46b> in <module>()
----> 1 from progressbar import ProgressBar
      2 
      3 num_images = metadata.shape[0]
      4 progress = ProgressBar(num_images)
      5 progress.start()

ImportError: No module named progressbar

Could you help me?

**Comment by TessFerrandez** [comment]
@gabit07 you can install it with 
pip install progressbar

**Comment by Gabit07** [comment]
> @Gabit07 you can install it with
> pip install progressbar

I've already installed it. When I import it in script imports well, but in the Jupiter notebook couldn't be imported, causes above error

**Comment by Gabit07** [comment]
> @Gabit07 you can install it with
> pip install progressbar

thank you for your quick reply

**Comment by Gabit07** [comment]
> @Gabit07 you can install it with
> pip install progressbar

when I run this code

!pip install progressbar
from progressbar import ProgressBar

Output it like this

Requirement already satisfied: progressbar in /usr/local/lib/python3.5/dist-packages (2.5)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-007c3af5f6ab> in <module>()
      1 get_ipython().system(u'pip install progressbar')
----> 2 from progressbar import ProgressBar

ImportError: No module named progressbar

**Comment by saadnajib** [comment]
You probably need to change your python environment of Jupyter notebook.
